Station/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('news.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'', include('comments.urls')),
]

comments/urls.py
# -*- coding:utf-8 -*-
#  made in ly
from django.conf.urls import url

from . import views

app_name = 'comments'

urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

news/urls.py

# -*- coding:utf-8 -*-
#  made in ly

from django.conf.urls import url
from . import views

app_name='news'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'index'),
  #  url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name="category"),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name="category"),
    url(r'^category_more_post/(?P<pk>[0-9]+)/$', views.category_more_post, name="category_more_post"),
    url(r'hot_topic/$', views.hot_topic, name='hot_topic'),
]

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('news.Post')

    def __str__(self):
        return self.text[:20]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
import markdown
from django.utils.html import strip_tags
# Create your models here.

#python_2_unicode_compatible 装饰器用于兼容python2
#分类
@python_2_unicode_compatible
class Category(models.Model):

    '''
        Django 要求模型必须继承models.Model类。
        Django 内置的全部类型可查看文档：
        https: // docs.djangoproject.com / en / 1.10 / ref / models / fields / # field-types
    '''
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

#标签
@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


#文章的封面插图
class Illustration(models.Model):
    Img = models.CharField(max_length=200)

    def _str_(self):
        return self.Img


#文章
@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()

    #下去试试 models.TimeField()

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField()

    #摘要，允许空值
    excerpt = models.CharField(max_length=200, blank=True)

    views = models.PositiveIntegerField(default=0)

    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User)
    img = models.ForeignKey(Illustration, blank=True)

    def __str__(self):

        return self.title

    def get_absolute_url(self):
        return reverse('news:post_detail',kwargs = {'pk': self.pk})

    class Meta:
        ordering = ["-created_time"]

    def increase_views(self):
        self.views +=1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])

            #先将markdown文本渲染成HTML文本，然后用strip_tags去掉HTML文本的全部HTML标签（为了防止文本中含有标签弄坏排版）
            #抽取前60个字符给excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:60]

        #调用父类的save方法将数据保存到数据库中
        super(Post,self).save(*args, **kwargs)

news/views.py
#coding=utf-8
from django.shortcuts import render, get_object_or_404
import markdown
# Create your views here.
from comments.forms import CommentForm
from django.http import HttpResponse
from .models import Post, Category, Tag, Illustration
from django.views.generic import ListView, DetailView
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.db.models import Q


class IndexView(ListView):
    model = Post

    template_name = 'news/index.html'

    context_object_name = 'post_list'

    def get_context_data(self, **kwargs):
        # 覆写该方法，以便我们获得自定义的模板变量

        context = super(IndexView, self).get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}

        left = []
        right = []

        left_has_more = False
        right_has_more = False
        first = False
        last = False

        page_number = page.number
        total_pages = paginator.num_pages

        # 获得整个分页的页码列表
        page_range = list(paginator.page_range)

        if page_number == 1:
            #            right = page_range[page_number:page_number + 1]
            right = page_range[page_number:page_number + 1]

            if right[-1] < total_pages - 1:
                right_has_more = True

            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0: page_number - 1]
            right = page_range[page_number:page_number + 1]

            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'last': last,
            'first': first,
        }

        return data

class PostDetailView(DetailView):
    model = Post
    template_name = 'news/post_detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆盖父类get方法
        # 父类get方法返回一个Httpresponse实例，
        # 之所以调用父类get方法，是因为只有当get方法被调用后，才有self.object属性，其值为Post模型实例            response = super(PostDetailView, self).get(request, *args, **kwargs)
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
         # 覆盖父类get_object方法

        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            #   'markdown.extensions.toc',
            TocExtension(slugify=slugify),
            ])

        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
       # 覆盖get_context_data 的目的是为了除了将post传递给模板外（DateilView已经帮我们完成）
        # 还要把评论表单、post下评论的列表传递给模板
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update(
            {
                'form': form,
                'comment_list': comment_list
            }
            )
        return context


def category(request, pk):
    # 记得在开始部分导入 Category 类
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')

    return render(request, 'news/category_detail.html', context={'post_list': post_list, 'whatcategory':cate, })

def category_more_post(request, pk):
    # 记得在开始部分导入 Category 类
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')

    return render(request, 'news/category_more_post.html', context={'post_list': post_list, 'whatcategory':cate, })


def hot_topic(request):
    return render(request, 'news/hot_topic.html', )

templates/news/category_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load news_tags %}
{% block main %}
  <section id="content">
  	<div class="top">
    	<div class="container">
            <div class="clearfix">
                <div class="grid3 first">
                    <h2>新闻列表</h2>
                        <h3><a href="{% url 'news:index' %}" class="current">首页</a>> {{ whatcategory.name }}</h3>
                        {% if error_msg %}
                            <p>{{ error_msg }}</p>
                        {% endif %}

                    {% for post in  post_list %}
                        <article class="post post-{{ post.pk }}">
                        {% if forloop.counter <= 5  %}
                            <div>
                                <ul class="list3">
                                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                                    {{ post.created_time }}
                                <li></li>

                                </ul>
                            </div>
                        {% endif %}
                        </article>
                    {% empty %}
                        该分类下暂无文章<br>
                    {% endfor %}
                    <a href="{% url 'news:category_more_post' whatcategory.pk %}" class="more">更多文章</a>
{#                     <a href="#" class="more">更多文章</a>#}
                </div>

                  <div class="grid9">
                      <h2>新闻导读</h2>
                      {% for post in post_list %}
                          {% if forloop.first %}

                            <div class="img-box">
                              <figure><img src="{{ post.img.Img }}" width=400px height=450px></figure>
                              <p>&nbsp;</p>
                                {{ post.img.Img }}
                              <p style="font-size:22px;">{{ post.title }}</p>
                                <p>{{ post.created_time }} &nbsp;&nbsp;{{ post.views }}&nbsp;&nbsp;&nbsp;{{ post.author }}</p>
                                <p>{{ post.excerpt }}</p>
                            </div>
                            <p><a href="{{ post.get_absolute_url }}" class="more">阅读详情</a></p>

                          {% endif %}
                        {% empty %}
                      {% endfor %}

                  </div>
            </div>
        </div>
    </div>
    <div class="middle">
    	<div class="container">
      	<div class="clearfix">

            {% get_popular_post as popular_post_list %}
         	<div class="grid3 first">
                <h2>热点摘要</h2>
                {% for post in popular_post_list %}
                    {% if forloop.first %}
                        <div class="img-wrap"><figure><img src="{% static 'news/images/2page-img3.jpg' %}" alt=""></figure></div>
                        <p>{{ post.views }}</p>
                        <p style="font-size:18px;">{{ post.excerpt }}</p>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                        <a href="{{ post.get_absolute_url }}" class="more">阅读详情</a>
                    {% endif %}
                {% endfor %}

            </div>
        	<div class="grid9">
                <h2>热门新闻</h2>
                <div class="clearfix">
                    <div class="grid3 first">
                        <ul class="list3">
                            {% for post in popular_post_list %}
                            {% if forloop.counter <= 3 %}
                                <li></li>
                                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="grid3">
                        <ul class="list3">
                            {% for post in popular_post_list %}
                            {% if forloop.counter > 3 and forloop.counter < 7 %}
                                <li></li>
                                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                            {% endif %}
                            {% endfor %}

                        </ul>
                    </div>
                    <div class="grid3">
                        <ul class="list3">
                           {% for post in popular_post_list %}
                            {% if forloop.counter > 6 and forloop.counter < 10 %}
                                <li></li>
                                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>


                </div>
                <p>&nbsp;</p>

{#                <p style="font-size:20px"><a href="#" class="more" >更多热门新闻</a></p>#}
            <p style="font-size:20px"><a href="{% url 'news:hot_topic' %}" class="more" >更多热门新闻</a></p>
            </div>

        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/news/category_more_post.html
{% extends 'base.html' %}
{% block main %}

<section id="content">
    <div class="top">
    	<div class="container">
            <h3><a href="{% url 'news:index' %}" class="current">首页</a>
                >
                <a href="{% url 'news:category' whatcategory.pk %}">{{ whatcategory.name }}</a>
            </h3>
    {% for post in post_list %}


        <article class="post post-{{ post.object.pk }}">
            <div>
                <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                <p>发布时间：{{ post.created_time }} &nbsp;&nbsp;&nbsp;阅读量：{{ post.views }}</p>
                <p>{{ post.excerpt }}</p>
            </div>
        </article>

    {% empty %}
        <p>{{ whatcategory.name }} 分类下暂时没有文章</p>
    {% endfor %}
        </div>
    </div>

</section>

{% endblock %}

templates/news/hot_topic.html
{% extends 'base.html' %}
{% block main %}

{% load news_tags %}

<section id="content">
    <div class="top">
    	<div class="container">
        <h3><a href="{% url 'news:index' %}" class="current">首页</a>> 热点新闻</h3>
        {% get_more_popular_post as post_list %}
            {% for post in post_list %}
                <div>
                    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                    <p>发布时间：{{ post.created_time }} &nbsp;&nbsp;&nbsp;阅读量：{{ post.views }}</p>
                    <p>{{ post.excerpt }}</p>
                </div>
            {% empty %}
                对不起，暂时没有文章
            {% endfor %}

        </div>
    </div>

    {% if query %}

        {% if page.has_previous or page.has_next %}

            <div>
                {% if page.has_previous %}
                    <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; 前一页
                {% if page.has_previous %}</a>{% endif %}
                |
                {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %} 后一页
                &raquo;{% if page.has_next %}</a>{% endif %}
            </div>

        {% endif %}

    {% endif %}

</section>


{% endblock %}

templates/news/index.html
{% extends 'base.html' %}
{% load static %}
{% load news_tags %}
{% block main %}

    <section id="content">
  	<div class="top">
    	<div class="container">
            <div class="clearfix">
                <section id="gallery">
                    <div class="pics">
                        <img src="{% static 'news/images/slide1.jpg' %}" alt="" width="495" height="329">
                        <img src="{% static 'news/images/slide3.jpg' %}" alt="" width="495" height="329">
                        <img src="{% static 'news/images/slide2.jpg' %}" alt="" width="495" height="329">
                        <img src="{% static 'news/images/slide4.jpg' %}" alt="" width="495" height="329">
                        <img src="{% static 'news/images/slide5.jpg' %}" alt="" width="495" height="329">

                    </div>
                    <a href="#" id="prev"></a>
                    <a href="#" id="next"></a>
                </section>
                <section id="intro">
          	        <div class="inner">
          	            <h2>看世界</h2>
          	            <h2><span>本月热点</span></h2>
                        {% get_now_day_hot as post_list %}
                        {% for post in post_list %}

                            {% if forloop.first %}
                                <p>{{ post.title }}<br />
                                {{ post.excerpt }}</p>
                            <a href="{{ post.get_absolute_url }}" class="extra-button">阅读详情</a>
                            {% endif %}
                        {% empty %}
                            本月暂未发布新闻
                        {% endfor %}


          	        </div>
                </section>
            </div>
        </div>
    </div>
    <div class="middle">

    	<div class="container">
      	    <div class="wrapper">
                <div class="grid3 first">

                <ul class="categories">
                    {% get_categories as category_list %}
                    <li><a href="#">导航</a></li>

                        {% for category in category_list %}
                            <li><a href="{% url 'news:category' category.pk %}">{{ category.name }}</a></li>
                        {% empty %}
                            sorry,暂无分类
                        {% endfor %}

                </ul>
                </div>
                <div class="grid9">
                    {% get_recent_posts as post_list %}
                    {% for post in post_list %}
                        {% if forloop.first %}

                         <h2>{{ post.title }} </h2>
                            &nbsp;&nbsp;阅读量：{{ post.views }}
                        <p>{{ post.excerpt }}</p>
                        <p><a href="{{ post.get_absolute_url }}" class="more">阅读详情</a></p>
                        <section class="images">
                            <figure><a href="#"><img src="{% static 'news/images/1page-img1.jpg' %}" alt=""></a></figure>
                          <figure><a href="#"><img src="{% static 'news/images/1page-img2.jpg' %}" alt=""></a></figure>
                          <figure><a href="#"><img src="{% static 'news/images/1page-img3.jpg' %}" alt=""></a></figure>

                        </section>
                        {% endif %}
                    {% empty %}
                        sorry,该类下没有文章
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
  </section>



{% endblock main %}

templates/news/post_detail.html
{% extends 'base.html' %}
{% block main %}
<section id="content">
    <article class="post post-1">
  	<div class="top">
    	<div class="container">
      	    <h2>{{ post.title }}</h2>
            <p>发布时间：{{ post.created_time }} &nbsp;&nbsp;&nbsp;&nbsp; 作者：{{ post.author }}</p>

            <p>{{ post.body|safe }}</p>

            <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                {% csrf_token %}
                <div class="">
                    <div class="">
                        <label for="{{ form.name.id_for_label }}">名字：</label>
                        {{ form.name }}
                        {{ form.name.errors }}


                        <label for="{{ form.email.id_for_label }}">邮箱：</label>
                        {{ form.email }}
                        {{ form.email.errors }}

                        <label for="{{ form.url.id_for_label }}">URL：</label>
                        {{ form.url }}
                        {{ form.url.errors }}
                    </div>
                    <div class="">
                        <label for="{{ form.text.id_for_label }}" >评论：</label>
                        {{ form.text }}
                        {{ form.text.errors }}
                        <br>

                          <button type="submit" class="">发表</button>

                    </div>
                </div>    <!-- row -->
            </form>

            <div>
                <ul class="comment-list list-unstyled">
                    <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                    {% for comment in comment_list %}
                        <li class="comment-item">
                            <span class="nickname">{{ comment.name }}</span>
                            <time class="submit-date">{{ comment.created_time }}</time>
                            <div class="text">
                                {{ comment.text }}
                            </div>
                        </li>
                    {% empty %}
                        暂无评论
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
    </article>
</section>

{% endblock %}